### PR TITLE
Always return a boolean value

### PR DESCRIPTION
**Pull request by nhunzaker**
I hit a snag writing `isPromise(undefinedThing) === false`, so I added a double-bang to the initial check to ensure that a boolean value is always returned.

### CODE REVIEW

**Comment by nathan7** [comment]
Landed! @ForbesLindesay, could you please `npm publish` v2.1.0?
I've tagged it and everything, but I don't have publish access.

**Comment by nhunzaker** [comment]
Thanks!

**Comment by nhunzaker** [comment]
Any news here? I'd love to have this!

**Comment by ForbesLindesay** [comment]
Published, and I've added @nathan7 as an owner on npm to make future publishing easier.

**Comment by nhunzaker** [comment]
Thanks!

**Pull request closed without merging**
